services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes:
      # при первом запуске скрипты из /docker-entrypoint-initdb.d/*.sql выполняются автоматически
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "testuser", "-d", "testdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGUSER: testuser
      PGPASSWORD: testpass
      PGDATABASE: testdb
      PGHOST: postgres
    volumes:
      - .:/app:cached
    ports:
      - "1234:1234"        # <- вот сюда
    # Оставляем контейнер "живым", чтобы workflow мог заходить внутрь и запускать тесты
    command: [ "sh", "-c", "/build/tests/run_tests.sh && tail -f /dev/null" ]
    # command: tail -f /dev/null

